### ISSUE TITLE
Procedures Problems

### ISSUE THREAD

**Issue by TearPelato** [MagicalAlexey/Generator-1.21.5#2]
i installed this plugin and changed the version of my mod and thi is the log.

Executing Gradle task: build 
Build info: MCreator 2025.1.13416, neoforge-1.21.5, 64-bit, 15710 MB, Windows 11, JVM 21.0.5, JAVA_HOME: C:\Program Files\Pylo\MCreator\jdk, started on: 2025-04-29-15:39:31 
 
Calculating task graph as no cached configuration is available for tasks: build 
> Configure project : 
Failed to parse MC version from NeoForge version 21.5.58-beta. Using capabilities of latest known Minecraft version with Minecraft version 1.21.5. 
> Task :jarJar NO-SOURCE 
> Task :processTestResources NO-SOURCE 
> Task :createMinecraftArtifacts 
Loaded 139 artifacts from C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\build\tmp\createMinecraftArtifacts\nfrt_artifact_manifest.properties 
DONE  Completed downloadJson in 0.03s 
REUSE Used cache of listLibraries in 0.00s 
DONE  Completed downloadClient in 0.04s 
DONE  Completed downloadClientMappings in 0.04s 
DONE  Completed downloadServer in 0.04s 
REUSE Used cache of mergeMappings in 0.00s 
REUSE Used cache of stripClient in 0.00s 
REUSE Used cache of extractServer in 0.00s 
REUSE Used cache of stripServer in 0.00s 
REUSE Used cache of merge in 0.00s 
REUSE Used cache of rename in 0.00s 
REUSE Used cache of decompile in 0.00s 
REUSE Used cache of inject in 0.00s 
REUSE Used cache of patch in 0.00s 
REUSE Used cache of applyNeoforgePatches in 0.00s 
RUN   Running external tool net.neoforged.jst:jst-cli-bundle:1.0.66 
> Task :processResources 
> Task :createMinecraftArtifacts 
DONE  Completed transformSources in 8.64s 
  WARNING: org.ow2.asm:asm:9.6 is not present in the artifact manifest 
138 items on the compile classpath 
0 items on the sourcepath 
Compiling 5922 source files 
DONE  Completed sourcesWithNeoForge in 9.18s 
Copied 0 resource files 
DONE  Completed recompile in 43.20s 
DONE  Completed compiledWithNeoForge in 10.85s 
DONE  Completed sourcesAndCompiledWithNeoForge in 3.03s 
Total runtime: 67.14s 
> Task :compileJava 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:47](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:47): error: cannot find symbol 
            if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem 
                                                                                                                            ^ 
  symbol:   class PickaxeItem 
  location: class PreciousGemsProcedure2Procedure 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:68](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:68): error: cannot find symbol 
            if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem && Blocks.ANCIENT_DEBRIS == (world.getBlockState(BlockPos.containing(x, y, z))).getBlock()) { 
                                                                                                                            ^ 
  symbol:   class PickaxeItem 
  location: class PreciousGemsProcedure2Procedure 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:88](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:88): error: cannot find symbol 
            if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem 
                                                                                                                            ^ 
  symbol:   class PickaxeItem 
  location: class PreciousGemsProcedure2Procedure 
3 errors 
> Task :compileJava FAILED 
FAILURE: Build failed with an exception. 
* What went wrong: 
Execution failed for task ':compileJava'. 
> Compilation failed; see the compiler output below. 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:47](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:47): error: cannot find symbol 
              if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem 
                                                                                                                              ^ 
    symbol:   class PickaxeItem 
    location: class PreciousGemsProcedure2Procedure 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:68](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:68): error: cannot find symbol 
              if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem && Blocks.ANCIENT_DEBRIS == (world.getBlockState(BlockPos.containing(x, y, z))).getBlock()) { 
                                                                                                                              ^ 
    symbol:   class PickaxeItem 
    location: class PreciousGemsProcedure2Procedure 
[C:\Users\HP\MCreatorWorkspaces\bacupperchepylofaschifo\src\main\java\net\mcreator\minecraftadditions\procedures\PreciousGemsProcedure2Procedure.java:88](file:///C:/Users/HP/MCreatorWorkspaces/bacupperchepylofaschifo/src/main/java/net/mcreator/minecraftadditions/procedures/PreciousGemsProcedure2Procedure.java:88): error: cannot find symbol 
              if ((entity instanceof LivingEntity _livEnt ? _livEnt.getMainHandItem() : ItemStack.EMPTY).getItem() instanceof PickaxeItem 
                                                                                                                              ^ 
    symbol:   class PickaxeItem 
    location: class PreciousGemsProcedure2Procedure 
  Note: Some input files use or override a deprecated API. 
  Note: Recompile with -Xlint:deprecation for details. 
  Note: Recompile with -Xlint:unchecked for details. 
  3 errors 
* Try: 
> Check your code and dependencies to fix the compilation error(s) 
> Run with --scan to get full insights. 
BUILD FAILED in 1m 16s 
3 actionable tasks: 3 executed 
Configuration cache entry stored. 
 
BUILD FAILED

**Comment by MagicalAlexey** [comment]
What kind of procedural blocks do you use?

**Comment by TearPelato** [comment]
it's a procedure for an enchant. that's the procedure.

![Image](https://github.com/user-attachments/assets/2791aae1-e208-44b1-9780-4df4e445cdb0)

**Comment by TearPelato** [comment]
i'm planning to port my mod in 1.21.5 with this plugin but this problem doesn't let me do that
